apiVersion: v1
kind: Service
metadata:
  name: ejbca-database-service
  labels:
    app: mariadb
spec:
  type: ClusterIP
  ports:
  - name: tcp-db-port
    port: 3306
    targetPort: 3306
  selector:
    app: mariadb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-statefulset
  labels:
    app: mariadb
    version: v1
spec:
  serviceName: "ejbca-database-service"
  replicas: 1 # how many replicas of pods we want to create
  selector:
    matchLabels:
      app: mariadb
  template: # blueprint for pods
    metadata:
      labels:
        app: mariadb # service will look for this label
    spec: # specification for pods
      containers:
        - name: mariadb
          image: mariadb:latest
          ports:
          - containerPort: 3306 #default one
          env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-secret
                key: mariadb-root-password
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ejbca-mariadb-secret
                key: ejbca-db-password
          - name: MARIADB_DATABASE
            value: ejbca
          - name: MARIADB_USER
            value: ejbca
          volumeMounts:
            - name: datadir
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10G
