apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ejbca.fullname" . }}
  labels:
    {{- include "ejbca.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ejbca.replicaCount }}
  selector:
    matchLabels:
      {{- include "ejbca.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.ejbca.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ejbca.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.ejbca.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ejbca.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.ejbca.image.repository }}:{{ .Values.ejbca.image.tag }}"
          imagePullPolicy: {{ .Values.ejbca.image.pullPolicy }}
          ports:
            {{- range .Values.ejbca.containerPorts }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol }}
            {{- end }}
          startupProbe:
            httpGet:
              port: 8081
              path: /ejbca/publicweb/healthcheck/ejbcahealth
            failureThreshold: 1000 # 50 * 2 seconds + 45-second delay gives 145 seconds for EJBCA to start
            periodSeconds: 2
            initialDelaySeconds: 45
          livenessProbe:
            httpGet:
              port: 8081
              path: /ejbca/publicweb/healthcheck/ejbcahealth
          env:
            - name: DATABASE_JDBC_URL
              value: "jdbc:mariadb://{{ .Values.database.service.name }}:{{ .Values.database.service.port }}/ejbca?characterEncoding=utf8"
            - name: DATABASE_USER
              value: {{ .Values.database.username }}
            - name: DATABASE_PASSWORD
              value: {{ .Values.database.password }}
            - name: PROXY_HTTP_BIND
              value: "{{ .Values.ejbca.proxyHttpBind }}"
            - name: LOG_AUDIT_TO_DB
              value: "{{ .Values.ejbca.logAuditToDatabase }}"
            {{ if .Values.ejbca.ingress.enabled }}
            - name: HTTPSERVER_HOSTNAME
              value: "{{ index .Values.ejbca.ingress.hosts 0 "host" }}"
            {{ end }}
            # - name: INITIAL_ADMIN
            #   value: {{ .Values.ejbca.initialAdmin }}
            - name: TLS_SETUP_ENABLED
              value: "simple"
          volumeMounts:
          {{- range .Values.ejbca.volumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.ejbca.reverseProxy.enabled }}
        - name: httpd
          image: "{{ .Values.ejbca.reverseProxy.image.repository }}:{{ .Values.ejbca.reverseProxy.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ejbca.reverseProxy.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8080
          volumeMounts:
            - name: httpd-configmap
              mountPath: /usr/local/apache2/conf/
            - name: reverse-proxy-tls
              mountPath: /usr/local/certs
            - name: cert-auth-ca
              mountPath: /usr/local/cacerts
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- end }}
      volumes:
      {{- range .Values.ejbca.volumes }}
        - name: {{ .name }}
          configMap: 
            name: {{ .configMapName }}
      {{- end }}
      {{- if .Values.ejbca.reverseProxy.enabled }}
        - name: httpd-configmap
          configMap: 
            name: httpd-configmap
        - name: reverse-proxy-tls
          secret:
            secretName: {{ .Values.ejbca.reverseProxy.tlsSecretName }}
        - name: cert-auth-ca
          secret:
            secretName: {{ .Values.ejbca.reverseProxy.authCASecretName }}
      {{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

